# Infrastructure addon for Exchange EWS Connector
# Adds NAT Gateway for internet connectivity from private subnets
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
    Default: exchange-sync

Resources:
  # Elastic IP for NAT Gateway
  NATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "${App}-${Env}-nat-gateway-eip"

  # NAT Gateway in the first public subnet
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: 
        Fn::Select:
          - 0
          - Fn::Split:
            - ','
            - Fn::ImportValue: !Sub ${App}-${Env}-PublicSubnets
      Tags:
        - Key: Name
          Value: !Sub "${App}-${Env}-nat-gateway"

  # Route table for private subnets to use NAT Gateway
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${App}-${Env}-VpcId
      Tags:
        - Key: Name
          Value: !Sub "${App}-${Env}-private-route-table"

  # Route to NAT Gateway for internet access
  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  # Associate route table with private subnets
  PrivateSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Fn::Select:
          - 0
          - Fn::Split:
            - ','
            - Fn::ImportValue: !Sub ${App}-${Env}-PrivateSubnets
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Fn::Select:
          - 1
          - Fn::Split:
            - ','
            - Fn::ImportValue: !Sub ${App}-${Env}-PrivateSubnets
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  # Output the Name parameter for reference
  WorkloadName:
    Description: "Name of the workload"
    Value: !Ref Name
  
  # Output NAT Gateway information
  NATGatewayId:
    Description: "NAT Gateway ID for internet connectivity"
    Value: !Ref NATGateway
    Export:
      Name: !Sub "${App}-${Env}-NATGatewayId"
  
  NATGatewayEIP:
    Description: "Elastic IP address of the NAT Gateway"
    Value: !Ref NATGatewayEIP
    Export:
      Name: !Sub "${App}-${Env}-NATGatewayEIP"