# IAM permissions for the Exchange sync job
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
    Default: exchange-sync

Resources:
  # IAM Managed Policy for Exchange sync permissions
  ExchangeSyncPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${App}-${Env}-${Name}-Policy"
      Description: "Permissions for Exchange EWS Connector"
      Roles:
        - !Sub "${App}-${Env}-${Name}-TaskRole"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # DynamoDB permissions - using wildcard since table is created dynamically
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:CreateTable
              - dynamodb:DescribeTable
              - dynamodb:TagResource
              - dynamodb:UntagResource
              - dynamodb:ListTagsOfResource
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/processed-emails*"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/processed-emails*/index/*"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${App}-${Env}-processed-emails*"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${App}-${Env}-processed-emails*/index/*"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/custom-connector-outlook-processed-emails*"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/custom-connector-outlook-processed-emails*/index/*"
          
          # Q Business permissions
          - Effect: Allow
            Action:
              - qbusiness:BatchPutDocument
              - qbusiness:BatchDeleteDocument
              - qbusiness:StartDataSourceSyncJob
              - qbusiness:StopDataSourceSyncJob
              - qbusiness:ListDataSourceSyncJobs
              - qbusiness:GetDataSourceSyncJob
            Resource: "*"
          
          # Parameter Store permissions - using existing paths for backwards compatibility
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/exchange-connector/${Env}/*"
          
          # CloudWatch Logs permissions
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"

Outputs:
  ExchangeSyncPolicyArn:
    Description: "ARN of the IAM managed policy for Exchange sync tasks"
    Value: !Ref ExchangeSyncPolicy